module.exports = task = {
  id: "1497",
  targetArea: "101 강남사업장",
  items: [
    {
      deliveryQuantity: 0,
      iStockID: "20191123",
      lineItemID: "1",
      originalItemID: "1",
      productID: "PALLET",
      selected: false,
      targetLogisticsArea: { id: "101-10", text: "원자재창고" },
      unitCode: "EA",
    },
    {
      deliveryQuantity: 1,
      iStockID: "20191127",
      lineItemID: "2",
      originalItemID: "2",
      productID: "WRAP",
      selected: false,
      targetLogisticsArea: { id: "101-10", text: "원자재창고" },
      unitCode: "MTR",
    },
    {
      deliveryQuantity: 1,
      iStockID: "20191127",
      lineItemID: "2-1",
      originalItemID: "2",
      productID: "WRAP",
      selected: false,
      targetLogisticsArea: { id: "101-10", text: "원자재창고" },
      unitCode: "MTR",
    },
    {
      deliveryQuantity: 1,
      iStockID: "20191127",
      lineItemID: "2-2",
      originalItemID: "2",
      productID: "WRAP",
      selected: false,
      targetLogisticsArea: { id: "101-10", text: "원자재창고" },
      unitCode: "MTR",
    },
    {
      deliveryQuantity: 0,
      iStockID: "20191120",
      lineItemID: "3",
      originalItemID: "3",
      productID: "CH01",
      selected: false,
      targetLogisticsArea: { id: "101-20", text: "반제품창고" },
      unitCode: "MTR",
    },
    {
      deliveryQuantity: 0,
      iStockID: "20191125",
      lineItemID: "4",
      originalItemID: "4",
      productID: "PSF01",
      selected: false,
      targetLogisticsArea: { id: "101-99", text: "불량창고" },
      unitCode: "MTR",
    },
    {
      deliveryQuantity: 1,
      iStockID: "20191122",
      lineItemID: "5",
      originalItemID: "5",
      productID: "LABEL-2.0",
      selected: false,
      targetLogisticsArea: { id: "101-10", text: "원자재창고" },
      unitCode: "MTR",
    },
    {
      deliveryQuantity: 1,
      iStockID: "20191122",
      lineItemID: "5-1",
      originalItemID: "5",
      productID: "LABEL-2.0",
      selected: false,
      targetLogisticsArea: { id: "101-10", text: "원자재창고" },
      unitCode: "MTR",
    },
  ],
};
